# Generated by Django 4.0.4 on 2022-05-20 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('termino', models.DateTimeField(verbose_name='Termino')),
                ('descricao', models.CharField(max_length=2000, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('termino', models.DateTimeField(verbose_name='Termino')),
                ('planejamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.planejamento')),
            ],
        ),
    ]
