# Generated by Django 4.0.4 on 2022-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='nome_planejamento',
            field=models.CharField(default=True, max_length=100, verbose_name='Nome do Planejamento'),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='descricao',
            field=models.CharField(max_length=2000, verbose_name='Descrição'),
        ),
    ]
