# Generated by Django 4.0.4 on 2022-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_planejamento_nome_planejamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='nome_planejamento',
            field=models.CharField(default='Nome do Planejamento', max_length=100, verbose_name='Nome do Planejamento'),
        ),
    ]
