# Generated by Django 4.0.4 on 2022-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_planejamento_nome_planejamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='nome_planejamento',
            field=models.CharField(max_length=100, verbose_name='Nome do Planejamento'),
        ),
    ]
